apiVersion: v1
kind: Pod
metadata:
  name: demo-kotlinmaven
  labels:
    role: webapp
spec:
  containers:
    - name: web
      image: ramon201/demo-kotlincreatedbyvc
      ports:
        - containerPort: 80
          name: web
          protocol: TCP