name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run tests
        run: mvn test
      - name: Package
        run: mvn -Dmaven.test.skip=true package
      - name: Try it!
        run: java -cp target/kotlin-maven-1.0-SNAPSHOT-jar-with-dependencies.jar com.mycompany.app.App
      - name: check java version
        run: java -version
      - name: maven project run
        run: mvn clean install
      - name: docker version
        run: |
          docker -v
          docker
          docker images -a
      - name: docker build
        run: |
          docker build . -t demo-kotlin2.0
          docker images -a
      - name: docker login
        run: docker login -u ${{ secrets.dockerhubusername}} -p ${{ secrets.dockerhubpassword}}
      - name: docker image push
        run: docker push demo-kotlin2.0
